name: Deploy dbt Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_2 }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER_2 }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD_2 }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE_2 }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt-snowflake
        run: pip install dbt-snowflake

      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "uspto_dbt:" > ~/.dbt/profiles.yml
          echo "  target: dev" >> ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    dev:" >> ~/.dbt/profiles.yml
          echo "      type: snowflake" >> ~/.dbt/profiles.yml
          echo "      account: $SNOWFLAKE_ACCOUNT" >> ~/.dbt/profiles.yml
          echo "      user: $SNOWFLAKE_USER" >> ~/.dbt/profiles.yml
          echo "      password: $SNOWFLAKE_PASSWORD" >> ~/.dbt/profiles.yml
          echo "      role: $SNOWFLAKE_ROLE" >> ~/.dbt/profiles.yml
          echo "      warehouse: USPTO_WH" >> ~/.dbt/profiles.yml
          echo "      database: USPTO_DB" >> ~/.dbt/profiles.yml
          echo "      schema: ANALYTICS" >> ~/.dbt/profiles.yml
          echo "      threads: 4" >> ~/.dbt/profiles.yml

      - name: Install dbt dependencies
        run: dbt deps --project-dir transformation/uspto_dbt

      - name: Generate documentation
        run: dbt docs generate --project-dir transformation/uspto_dbt

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: transformation/uspto_dbt/target  # Specify the target directory containing generated documentation
          branch: gh-pages # Define the target branch for GitHub Pages deployment
