name: SQL Quality Check (SQLFluff)

on:
  push:
    branches:
      - main
      - orchestration
  pull_request:

jobs:
  lint-sql:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install sqlfluff==3.0.0
          pip install sqlfluff-templater-dbt==3.0.0
          pip install dbt-snowflake==1.8.0
          
      - name: Create Dummy Profile for dbt
              # We create a fake profile so SQLFluff can "compile" the code
              # We don't need real passwords just to check syntax!
        run: |
          mkdir -p ~/.dbt
          echo "uspto_dbt:" > ~/.dbt/profiles.yml
          echo "  target: prod" >> ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    prod:" >> ~/.dbt/profiles.yml
          echo "      type: snowflake" >> ~/.dbt/profiles.yml
          echo "      account: dummy" >> ~/.dbt/profiles.yml
          echo "      user: dummy" >> ~/.dbt/profiles.yml
          echo "      password: dummy" >> ~/.dbt/profiles.yml
          echo "      role: dummy" >> ~/.dbt/profiles.yml
          echo "      database: dummy" >> ~/.dbt/profiles.yml
          echo "      warehouse: dummy" >> ~/.dbt/profiles.yml
          echo "      schema: dummy" >> ~/.dbt/profiles.yml
          echo "      threads: 1" >> ~/.dbt/profiles.yml

      - name: Run SQLFluff Lint
        # This scans only the 'models' directory to save time
        run: |
          sqlfluff lint transformation/uspto_dbt/models --dialect snowflake